version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/nginx.key:/etc/ssl/nginx.key
      - ./nginx/ssl/nginx.pem:/etc/ssl/nginx.pem
      - ../frontend/dist/:/usr/share/nginx/html/
    ports:
      - 443:443
    networks:
      - "blog"     
  backend:
    image: deployment_backend:latest
    pull_policy: "never"
    container_name: blog_backend
    restart: always
    ports: 
      - "8080:8080"
    networks:
      - "blog"    

networks:
  blog:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24  
